In [10]:
import pandas as pd
from sklearn.model_selection import GridSearchCV
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# load the data from the CSV file
data = pd.read_csv("D:\dataset\cardiio.csv")
df = data.iloc[:500]
df.head()

,Unnamed: 0,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [5]:
# split the data into features and target variable
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [6]:
# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
# define the parameter grid
param_grid = {'C': [0.1, 1, 10], 'gamma': [0.1, 1, 10]}

In [9]:
# create a SVM model
svm_model = svm.SVC()

# perform grid search to find the best hyperparameters
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(svm_model, param_grid, cv=3)

grid_search.fit(X_train, y_train)
# print the best hyperparameters and the corresponding score
print("Best hyperparameters: ", grid_search.best_params_)
print("Best score: ", grid_search.best_score_)

Best hyperparameters:  {'C': 0.1, 'gamma': 0.1}
Best score:  0.5175064526989115